### ISSUE TITLE
Unable to load Talend component - tGoogleAnalyticsInput

### ISSUE THREAD

**Issue by SwatiSood** [jlolling/talendcomp_tGoogleAnalyticsInput#9]
Hi,
I tried to download the component - tGoogleAnalyticsInput from the exchange. When I press the "install" button, the color of install changes from blue to purple, but it will just not install. Nothing really happens after that. When I try to open the job on Talend, I get a message – “Some of the components are not loaded - tGoogleAnalyticsInput”. 

The log files gives :
ENTRY org.talend.platform.logging 4 0 2020-08-19 17:08:49.309
!MESSAGE 2020-08-19 17:08:49,308 ERROR org.talend.commons.exception.CommonExceptionHandler  - error in opening zip file

!STACK 0
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:126)
	at org.talend.designer.components.exchange.jobs.ComponentInstaller.unzip(ComponentInstaller.java:45)
	at org.talend.designer.components.exchange.ui.actions.DownloadComponenentsAction$DownloadJob.afterDownload(DownloadComponenentsAction.java:361)
	at org.talend.designer.components.exchange.ui.actions.DownloadComponenentsAction$DownloadJob.downloadExtension(DownloadComponenentsAction.java:301)
	at org.talend.designer.components.exchange.ui.actions.DownloadComponenentsAction$DownloadJob.run(DownloadComponenentsAction.java:265)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Attaching the screenshots.

![s1](https://user-images.githubusercontent.com/51931664/90728383-1b23ff00-e2c5-11ea-94c5-2e86e2c80bda.jpg)
![s2](https://user-images.githubusercontent.com/51931664/90728399-1eb78600-e2c5-11ea-98da-4ca4f442a7e8.jpg)
![s3](https://user-images.githubusercontent.com/51931664/90728480-41e23580-e2c5-11ea-835f-7512f44c44b7.jpg)

Is it something that you can look into?

Regards,
Swati Sood

**Comment by jlolling** [comment]
It is not an issue of the component instead of Talend Exchange.
I have just updated the component to version 8.10 to get rid of the out dated log4j logging framework.
Please try it again with Talend Exchange. If this does not work, you can download the component also here from Github.
Change to the Code tab on the top and at the right side you find the release download link.

**Comment by SwatiSood** [comment]
Hi Jan,
I realized it was an issue with Talend Exchange and not this component.
Talend Support team guided me in showing how i can configure custom components into my Talend studio. 
This is working for me now.  

Thanks for replying.

Regards,
Swati Sood

**Comment by jlolling** [comment]
Thank for feedback!
